/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonTouch1Filled: typeof import('~icons/carbon/touch1-filled')['default']
    IClarityBetaSolid: typeof import('~icons/clarity/beta-solid')['default']
    IHealthiconsQuestionMark: typeof import('~icons/healthicons/question-mark')['default']
    IIconoirCancel: typeof import('~icons/iconoir/cancel')['default']
    IMajesticonsLightbulbShine: typeof import('~icons/majesticons/lightbulb-shine')['default']
    IMakiArrow: typeof import('~icons/maki/arrow')['default']
    IPhShareFill: typeof import('~icons/ph/share-fill')['default']
    ISolarRestartSquareBold: typeof import('~icons/solar/restart-square-bold')['default']
    Lightbox: typeof import('./src/components/Lightbox.vue')['default']
    Playboard: typeof import('./src/components/Playboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleDeclaration: typeof import('./src/components/RuleDeclaration.vue')['default']
  }
}
